name: "pre-commit checks"
description: "Runs pre-commit checks on repository"
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --show-diff-on-failure --all-files
